version: '3.4'

services:

  test_chatbot:
    container_name: test_chatbot
    build:
      context: ./mini_chatbot
      dockerfile: Dockerfile-dev
    volumes:
      - './mini_chatbot:/usr/src/app'
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.config.DevelopmentConfig
      - SECRET_KEY=my_precious

  tnginx:
    container_name: tnginx
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - test_chatbot